Repository enflujo/imagina-inclusion-migrantes, pull requests merged in 2024-04, with the labels that each got.

#24 🕷️ Agregar coordenadas municipios y voronoi
  aplicaciones/procesador/datos/Inclusion scores nationwide180324.xlsx
  aplicaciones/procesador/datos/municipios.json
  aplicaciones/procesador/datos/municipios_colombia.xlsx
  aplicaciones/procesador/fuente/aplicacion.ts
  aplicaciones/procesador/fuente/utilidades/ayudas.ts
  aplicaciones/procesador/fuente/utilidades/lugaresColombia.ts
  aplicaciones/procesador/tipos.ts
  aplicaciones/procesador/tsconfig.json
  aplicaciones/www/package.json
  aplicaciones/www/public/inclusion-municipios.json
  aplicaciones/www/src/cerebros/datos.ts
  aplicaciones/www/src/componentes/Mapa.vue
  yarn.lock
Labels: api :evergreen_tree:, front-end :art:

#32 🖌️ Estilos
  aplicaciones/www/fuente/scss/estilos.scss
  aplicaciones/www/src/Aplicacion.vue
  aplicaciones/www/src/cerebros/datos.ts
  aplicaciones/www/src/componentes/Comparacion.vue
  aplicaciones/www/src/componentes/Lista.vue
  aplicaciones/www/src/componentes/Mapa.vue
  aplicaciones/www/src/componentes/Simulacion/Bola.ts
  aplicaciones/www/src/componentes/Simulacion/Sim.ts
  aplicaciones/www/src/componentes/Simulacion/SimEvent.ts
  aplicaciones/www/src/componentes/Simulacion/index.vue
  aplicaciones/www/src/estaticos/_constantes.scss
  aplicaciones/www/src/estaticos/estilos.scss
  aplicaciones/www/src/paginas/Inicio.vue
Labels: front-end :art:

#37 🐛 Lugares seleccionados en lista
  aplicaciones/www/src/cerebros/datos.ts
  aplicaciones/www/src/componentes/Buscador.vue
  aplicaciones/www/src/componentes/Lista.vue
  aplicaciones/www/src/componentes/Simulacion/index.vue
  aplicaciones/www/src/paginas/Inicio.vue
Labels: mejora :ant:, ui :ocean:

#45 💖 Ajustes de color, márgenes, mapa, botones, bolas
  aplicaciones/www/public/imgs/boton_alfabetico.svg
  aplicaciones/www/public/imgs/boton_alfabetico_2.svg
  aplicaciones/www/public/imgs/boton_bajar.svg
  aplicaciones/www/public/imgs/boton_bajar_2.svg
  aplicaciones/www/public/imgs/boton_subir.svg
  aplicaciones/www/public/imgs/boton_subir_2.svg
  aplicaciones/www/src/Aplicacion.vue
  aplicaciones/www/src/cerebros/constantes.ts
  aplicaciones/www/src/componentes/Buscador.vue
  aplicaciones/www/src/componentes/Comparacion.vue
  aplicaciones/www/src/componentes/Lista.vue
  aplicaciones/www/src/componentes/Mapa.vue
  aplicaciones/www/src/componentes/Simulacion/Bola.ts
  aplicaciones/www/src/componentes/Simulacion/index.vue
  aplicaciones/www/src/enrutador/index.ts
  aplicaciones/www/src/estaticos/_constantes.scss
  aplicaciones/www/src/estaticos/estilos.scss
  aplicaciones/www/src/paginas/Creditos.vue
  aplicaciones/www/src/utilidades/ayudas.ts
Labels: ui :ocean:

#42 ⚖️ Comparaciones
  aplicaciones/www/src/componentes/Comparacion.vue
Labels: front-end :art:
